name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 🚀 Vérifie que le commit contient une fusée
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Dernier message de commit: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" != *🚀* ]]; then
          echo "❌ Le message de commit doit contenir une fusée 🚀"
          exit 1
          fi

      - name: Vérifier les dépendances circulaires
        run: python3 Scripts/check_circular_dependencies.py
        
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: ☀️ Résultat des tests
        if: success()
        run: echo "✅ Tous les tests ont réussi ! ☀️"

      - name: 🌩️ Résultat des tests
        if: failure()
        run: echo "❌ Certains tests ont échoué... 🌩️"
        