name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: 🚀 Vérifie que le commit contient une fusée
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Dernier message de commit: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" != *🚀* ]]; then
          echo "❌ Le message de commit doit contenir une fusée 🚀"
          exit 1
          fi
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: 👽 Poster un commentaire alien en cas d’échec
        if: failure() && github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👽 **Humain, ton code est incompréhensible pour ma civilisation.**
            Peux-tu ajouter des tests pour que nous puissions le décoder ? 🤖🛠️

            _Ce message interstellaire a été généré automatiquement par le Grand Conseil des GitHub Actions._
            - name: ☀️ Résultat des tests
        if: success()
        run: echo "✅ Tous les tests ont réussi ! ☀️"

      - name: 🌩️ Résultat des tests
        if: failure()
        run: echo "❌ Certains tests ont échoué... 🌩️"